### ISSUE TITLE
Professional photograph of house on a hill, surrounded by trees, while it rains, high resolution, high quality

### ISSUE THREAD

**Issue by lilian-benoit** [oracle-samples/sd4j#9]
I realized actions that described on README.md and I launched this command.

`mvn package exec:exec -DmodelPath=../../runwayml/stable-diffusion-v1-5/`

I tested first example and i obtained this exception.

```
déc. 30, 2023 11:22:45 PM com.oracle.labs.mlrg.sd4j.SD4J generateImage
INFOS: Generating image for 'Wildlife photograph of an astronaut riding a horse in the desert', with guidance
Exception in thread "Thread-2" java.lang.IllegalArgumentException: Buffer has different capacity than the shape expects. Buffer.capacity = 118272, numElements = -1
	at com.oracle.labs.mlrg.sd4j.Tensor.<init>(Tensor.java:90)
	at com.oracle.labs.mlrg.sd4j.FloatTensor.<init>(FloatTensor.java:63)
	at com.oracle.labs.mlrg.sd4j.TextEmbedder.embedTokens(TextEmbedder.java:195)
	at com.oracle.labs.mlrg.sd4j.TextEmbedder.embedText(TextEmbedder.java:274)
	at com.oracle.labs.mlrg.sd4j.TextEmbedder.embedTextAndUncond(TextEmbedder.java:221)
	at com.oracle.labs.mlrg.sd4j.SD4J.generateImage(SD4J.java:163)
	at com.oracle.labs.mlrg.sd4j.SD4J.generateImage(SD4J.java:139)
	at com.oracle.labs.mlrg.sd4j.SD4JApp$SwingDisplayWindow.lambda$create$4(SD4JApp.java:391)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

for information, i use OpenJDK 17.0.9

What is this problem ?

**Comment by Craigacp** [comment]
Looks like the ONNX export process doesn't always set the dimension I was using to detect if it's an SD v1.5 or SD v2 model, so it set the dimension to `-1` which is the default for unknown size dimensions in ONNX Runtime and that error propagated giving a bad error message.

I've fixed it by merging in this PR so that if autodetection fails it has a user configurable fallback value, but I also made the autodetection more robust by using a value which should be more consistently set.

**Comment by lilian-benoit** [comment]
It work on my machine.
Thanks a lot !
